version: "3.8"

volumes:
  db:
    driver: local

services:
  noah-db:
    container_name: noah-db
    image: postgres:16
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=noah
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  noah:
    container_name: noah
    restart: always
    image: "airdb/noah:latest"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8080:8080/tcp"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    #command: sleep 3600
    depends_on:
      - noah-db
    links:
      - noah-db
