version: '3.3'

services:
  apigw:
    container_name: apigw
    restart: always
    image: 'airdb/apigw:latest'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080/tcp"
    volumes:
      - ./config.yaml:/app/config.yaml:ro