# fly.toml app configuration file generated for bumu on 2023-05-20T01:00:34+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bumu"
primary_region = "sin"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
