version: '3'

vars:
  SERVICE: noah
  DATE:
    sh: date "+%Y.%m%d.%H%M"
  
tasks:
  default:
    desc: Show help messages
    silent: true
    cmds:
      - echo "Welcome to use go-task!"
      - echo
      - |
        echo "Available tasks:"
        task --list | awk 'NR>1 {print "  " $0}'

  local:
    desc: Run locally
    cmds:
      - go run main.go run -c config.local.yaml

  build:
    desc: Build binary
    cmds:
      - go build -o main main.go

  buf:
    desc: Run buf generate
    dir: apis
    cmds:
      - buf generate

  docker-build:
    desc: Build or rebuild docker image
    cmds:
      - docker compose build {{.SERVICE}}
  
  docker-push:
    desc: Push image to docker hub
    cmds:
      - docker push airdb/noah:latest
      - docker tag airdb/noah:latest airdb/noah:{{.DATE}}
      - docker push airdb/noah:{{.DATE}}

  up:
    desc: Start service in docker
    cmds:
      - docker compose up -d {{.SERVICE}} --force-recreate

  start:
    desc: Start service
    cmds:
      - docker compose start {{.SERVICE}}

  stop:
    desc: Stop service
    cmds:
      - docker compose stop {{.SERVICE}}

  bash:
    desc: Enter bash
    cmds:
      - docker compose exec {{.SERVICE}} bash

  logs:
    desc: View service logs
    cmds:
      - docker compose logs -f {{.SERVICE}}

  dbup:
    desc: Start database service
    cmds:
      - docker compose up -d {{.SERVICE}}-db --force-recreate

  dbclean:
    desc: Remove database container
    cmds:
      - docker compose rm -f {{.SERVICE}}-db
      # - docker volume rm {{.SERVICE}}-db

  dbbash:
    desc: Enter database shell
    cmds:
      - docker compose exec {{.SERVICE}}-db bash -c "psql -Upostgres"